/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vien
 */

import java.awt.Component;
import java.awt.event.KeyEvent;
import oopproj.SubClass_Child;
import java.awt.TextField;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import org.json.JSONException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;



public class PosOOP extends javax.swing.JFrame {

    private JTextField cleartext;
    private double iTotal;

    /**
     * Creates new form PosOOP
     */
    public PosOOP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jfDrinks = new javax.swing.JTextField();
        jfMD = new javax.swing.JTextField();
        jfMeals = new javax.swing.JTextField();
        jtCostMeal = new javax.swing.JLabel();
        jtCostDrinks = new javax.swing.JLabel();
        jtTotalCost = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jtWater = new javax.swing.JLabel();
        jtOrangeJuice = new javax.swing.JLabel();
        jtCoke = new javax.swing.JLabel();
        jtCoffee = new javax.swing.JLabel();
        jtHotChocolate = new javax.swing.JLabel();
        jtVanillaShake = new javax.swing.JLabel();
        jtTax7 = new javax.swing.JLabel();
        jfWater = new javax.swing.JTextField();
        jfJuice = new javax.swing.JTextField();
        jfCoke = new javax.swing.JTextField();
        jfCoffee = new javax.swing.JTextField();
        jfHotChoco = new javax.swing.JTextField();
        jfVanillaShake = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtReceipt = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        BTotal = new javax.swing.JButton();
        BReceipt = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        BExit = new javax.swing.JButton();
        jfPayment = new javax.swing.JTextField();
        jcbPayment = new javax.swing.JComboBox<>();
        BPay = new javax.swing.JButton();
        jfChange = new javax.swing.JTextField();
        jtChange = new javax.swing.JLabel();
        bPrint = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jtRice = new javax.swing.JLabel();
        jtSisig = new javax.swing.JLabel();
        jtPorkSinigang = new javax.swing.JLabel();
        jtFriedChicken = new javax.swing.JLabel();
        jtSpaghetti = new javax.swing.JLabel();
        jtCarbonara = new javax.swing.JLabel();
        jtTax9 = new javax.swing.JLabel();
        jfRice = new javax.swing.JTextField();
        jfSisig = new javax.swing.JTextField();
        jfSinigang = new javax.swing.JTextField();
        jfFriedChicken = new javax.swing.JTextField();
        jfSpag = new javax.swing.JTextField();
        jfCarbonara = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jfSubTotal = new javax.swing.JTextField();
        jfTotal = new javax.swing.JTextField();
        jfTax = new javax.swing.JTextField();
        jtTax = new javax.swing.JLabel();
        jtSubTotal = new javax.swing.JLabel();
        jtTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 12));

        jfDrinks.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jfDrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jfMD.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jfMD.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jfMeals.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jfMeals.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtCostMeal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtCostMeal.setText("Cost of Meals");

        jtCostDrinks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtCostDrinks.setText("Cost of Drinks");

        jtTotalCost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtTotalCost.setText("Total cost");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtTotalCost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfMD, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtCostDrinks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(jfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtCostMeal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfMeals, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfMeals, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCostMeal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCostDrinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTotalCost))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 450, 160));

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 12));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 50)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant Management System");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-11-22 233046.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1340, 110));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 12));

        jtWater.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtWater.setText("Water ");

        jtOrangeJuice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtOrangeJuice.setText("Orange Juice");

        jtCoke.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtCoke.setText("Coke");

        jtCoffee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtCoffee.setText("Coffee");

        jtHotChocolate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtHotChocolate.setText("Hot Chocolate");

        jtVanillaShake.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtVanillaShake.setText("Vanilla Milk Shake");

        jtTax7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jtTax7.setText("DRINKS");

        jfWater.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfWater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfWater.setText("0");

        jfJuice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfJuice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfJuice.setText("0");

        jfCoke.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfCoke.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfCoke.setText("0");

        jfCoffee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfCoffee.setText("0");

        jfHotChoco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfHotChoco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfHotChoco.setText("0");

        jfVanillaShake.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfVanillaShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfVanillaShake.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtVanillaShake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(jfVanillaShake, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtWater)
                            .addComponent(jtOrangeJuice)
                            .addComponent(jtCoke)
                            .addComponent(jtCoffee)
                            .addComponent(jtHotChocolate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfWater, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfJuice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfCoke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfCoffee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfHotChoco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jtTax7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtTax7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtWater, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfWater, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtOrangeJuice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfJuice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCoke, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfCoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtCoffee, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtHotChocolate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfHotChoco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtVanillaShake)
                    .addComponent(jfVanillaShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 430, 320));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 12));

        jtReceipt.setColumns(20);
        jtReceipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtReceipt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 440, 490));

        jPanel7.setBackground(new java.awt.Color(204, 102, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 0), 12));

        BTotal.setBackground(new java.awt.Color(204, 204, 204));
        BTotal.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        BTotal.setText("Total");
        BTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTotalActionPerformed(evt);
            }
        });

        BReceipt.setBackground(new java.awt.Color(204, 204, 204));
        BReceipt.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        BReceipt.setText("Receipt");
        BReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReceiptActionPerformed(evt);
            }
        });

        BReset.setBackground(new java.awt.Color(204, 204, 204));
        BReset.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });

        BExit.setBackground(new java.awt.Color(204, 204, 204));
        BExit.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        BExit.setForeground(new java.awt.Color(255, 0, 0));
        BExit.setText("Exit");
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });

        jfPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jfPayment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfPaymentActionPerformed(evt);
            }
        });

        jcbPayment.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        jcbPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< SELECT >", "CASH", "GCASH", "CREDIT CARD" }));

        BPay.setBackground(new java.awt.Color(204, 204, 204));
        BPay.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        BPay.setText("Pay");
        BPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPayActionPerformed(evt);
            }
        });

        jfChange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jfChange.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtChange.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtChange.setText("Change");

        bPrint.setBackground(new java.awt.Color(204, 204, 204));
        bPrint.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        bPrint.setText("Print");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jcbPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtChange))
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfChange, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jfPayment))
                .addGap(41, 41, 41)
                .addComponent(BPay, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(BReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BReset, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BExit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTotal)
                    .addComponent(BReset)
                    .addComponent(BExit)
                    .addComponent(BReceipt)
                    .addComponent(BPay)
                    .addComponent(bPrint))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcbPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jfPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtChange))
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 1340, 90));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 12));

        jtRice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtRice.setText("Rice ");

        jtSisig.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtSisig.setText("Pork sisig");

        jtPorkSinigang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtPorkSinigang.setText("Pork sinigang");

        jtFriedChicken.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtFriedChicken.setText("Fried Chicken");

        jtSpaghetti.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtSpaghetti.setText("Spaghetti");

        jtCarbonara.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtCarbonara.setText("Carbonara");

        jtTax9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jtTax9.setText("MEALS");

        jfRice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfRice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfRice.setText("0");
        jfRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfRiceActionPerformed(evt);
            }
        });

        jfSisig.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfSisig.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfSisig.setText("0");

        jfSinigang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfSinigang.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfSinigang.setText("0");

        jfFriedChicken.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfFriedChicken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfFriedChicken.setText("0");

        jfSpag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfSpag.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfSpag.setText("0");

        jfCarbonara.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jfCarbonara.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jfCarbonara.setText("0");
        jfCarbonara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfCarbonaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtPorkSinigang)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtCarbonara)
                                .addComponent(jtSpaghetti)
                                .addComponent(jtFriedChicken)
                                .addComponent(jtSisig)))
                        .addGap(2, 149, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtRice, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfCarbonara, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfRice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfSisig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfSinigang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfFriedChicken, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfSpag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jtTax9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtTax9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfRice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtRice, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfSisig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtSisig))
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfSinigang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPorkSinigang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfFriedChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtFriedChicken))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfSpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtSpaghetti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfCarbonara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCarbonara))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 450, 320));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 12));

        jfSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jfSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jfTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jfTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jfTax.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jfTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtTax.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtTax.setText("Tax");

        jtSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtSubTotal.setText("SubTotal");

        jtTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtTotal.setText("Total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jtTax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jfTax, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jtSubTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(jfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTax)
                    .addComponent(jfTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtSubTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtTotal)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 430, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jfRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfRiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfRiceActionPerformed

    private void jfCarbonaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfCarbonaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfCarbonaraActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        // TODO add your handling code here:
        JTextField cleartext = null;
        
        for (Component c:jPanel8.getComponents()) {
            if(c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext =(JTextField)c;
                cleartext.setText("0");
            }
        }      
        
        //------------------------------------------------------------------    
        
        for (Component c:jPanel4.getComponents()) {
            if(c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext =(JTextField)c;
                cleartext.setText("0");
            }
        }      
        
        //------------------------------------------------------------------ 
        
        for (Component c:jPanel1.getComponents()) {
            if(c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext =(JTextField)c;
                cleartext.setText("");
            }
        }      
        
        //------------------------------------------------------------------ 
        
        for (Component c:jPanel3.getComponents()) {
            if(c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext =(JTextField)c;
                cleartext.setText("");
            }
        }      
        
        //------------------------------------------------------------------ 
        
        for (Component c:jPanel7.getComponents()) {
            if(c.getClass().toString().contains("javax.swing.JTextField")) {
                cleartext =(JTextField)c;
                cleartext.setText("");
            }
        }      
        
        //------------------------------------------------------------------
                
            jtReceipt.setText(null);
                
    }//GEN-LAST:event_BResetActionPerformed

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
        // TODO add your handling code here:
        SubClass_Child iExit = new SubClass_Child();
        iExit.iExitSystem();
        
    }//GEN-LAST:event_BExitActionPerformed

    private void BTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTotalActionPerformed
        // TODO add your handling code here:
        
        
        SubClass_Child ItemCost = new SubClass_Child();
        
        double iTax, iSubTotal, iTotal;
        
        ItemCost.tRice = ItemCost.Rice * Double.parseDouble(jfRice.getText());
        ItemCost.tSisig = ItemCost.Sisig * Double.parseDouble(jfSisig.getText());
        ItemCost.tSinigang = ItemCost.Sinigang * Double.parseDouble(jfSinigang.getText());
        ItemCost.tFriedChicken = ItemCost.FriedChicken * Double.parseDouble(jfFriedChicken.getText());
        ItemCost.tSpag = ItemCost.Spag * Double.parseDouble(jfSpag.getText());
        ItemCost.tCarbonara = ItemCost.Carbonara * Double.parseDouble(jfCarbonara.getText());
        
        ItemCost.tWater = ItemCost.Water * Double.parseDouble(jfWater.getText());
        ItemCost.tJuice = ItemCost.Juice * Double.parseDouble(jfJuice.getText());
        ItemCost.tCoke = ItemCost.Coke * Double.parseDouble(jfCoke.getText());
        ItemCost.tCoffee = ItemCost.Coffee * Double.parseDouble(jfCoffee.getText());
        ItemCost.tHotChoco = ItemCost.HotChoco * Double.parseDouble(jfHotChoco.getText());
        ItemCost.tVanillaShake = ItemCost.VanillaShake * Double.parseDouble(jfVanillaShake.getText());
        
        iSubTotal = ItemCost.GetAmount();
        iTax = ItemCost.cFindTax(iSubTotal);
        iTotal = iSubTotal + iTax;
        
        String SubTotal = String.format("₱ %.2f", iSubTotal);
        jfSubTotal.setText(SubTotal);
        
        String Tax = String.format("₱ %.2f", iTax);
        jfTax.setText(Tax);
        
        String Total = String.format("₱ %.2f", iTotal);
        jfTotal.setText(Total);
        
        String Meals = String.format("₱ %.2f", ItemCost.tMeals);
        jfMeals.setText(Meals);
        
        String Drinks = String.format("₱ %.2f", ItemCost.tDrinks);
        jfDrinks.setText(Drinks);
        
        String TotalCost = String.format("₱ %.2f", ItemCost.tMD);
        jfMD.setText(TotalCost);
        
        
        
    }//GEN-LAST:event_BTotalActionPerformed

    private void BReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReceiptActionPerformed
         
        FileWriter fw = null;
        try {
            fw = new FileWriter("Receipt.txt", true);
        } catch (IOException ex) {
            Logger.getLogger(PosOOP.class.getName()).log(Level.SEVERE, null, ex);
        }
         PrintWriter out = null;

         out = new PrintWriter(fw);
         // TODO add your handling code here:
         int refs = 1325 + (int) (Math.random() * 4238);
         Calendar timer = Calendar.getInstance();
         timer.getTime();
         SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
         tTime.format(timer.getTime());
         SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
         tDate.format(timer.getTime());
         jtReceipt.append("\tRestaurant Management System\n\n" + "Reference:\t\t\t" + refs +
                 
                 "\n-------------------------------------------------\n" +
                         "Item                            Amount" + "\n" +
                         "\nCost of Meals:\t\t\t" + jfMeals.getText() + "\n\n" +
                                 "Cost of Drinks:\t\t\t" + jfDrinks.getText() + "\n\n" +
                                         "Total cost:\t\t\t" + jfMD.getText() + "\n\n" +
                                                 
                                                 "-------------------------------------------------" + "\n\n" +
                                                 "VAT:\t\t\t\t" + jfTax.getText() + "\n\n" +
                                                         "SubTotal:\t\t\t" + jfSubTotal.getText() + "\n\n" +
                                                                 "Total:\t\t\t\t" + jfTotal.getText() + "\n\n" +
                                                                         
                                                                         "-------------------------------------------------" + "\n\n" +
                                                                         "Cash:\t\t\t\t" + "₱ " + jfPayment.getText() + "\n\n\n" +
                                                                                 "Change:\t\t\t\t" + jfChange.getText() + "\n\n\n" +
                                                                                         "-------------------------------------------------" +
                                                                                         "\nDate: " + tDate.format(timer.getTime()) +
                 "\tTime: " + tTime.format(timer.getTime()) +
                 "\n\nThank you.. Enjoy your Meal..."
         );
         if (out != null) {
             try {
                 out.close();
             } catch (Exception e) {
                 e.printStackTrace();
             }
         
         }   
    
    }//GEN-LAST:event_BReceiptActionPerformed

    private void BPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPayActionPerformed
        // TODO add your handling code here:
        SubClass_Child ItemCost = new SubClass_Child();
        
    double payment, change, iSubTotal, iTax;
    
    ItemCost.tRice = ItemCost.Rice * Double.parseDouble(jfRice.getText());
        ItemCost.tSisig = ItemCost.Sisig * Double.parseDouble(jfSisig.getText());
        ItemCost.tSinigang = ItemCost.Sinigang * Double.parseDouble(jfSinigang.getText());
        ItemCost.tFriedChicken = ItemCost.FriedChicken * Double.parseDouble(jfFriedChicken.getText());
        ItemCost.tSpag = ItemCost.Spag * Double.parseDouble(jfSpag.getText());
        ItemCost.tCarbonara = ItemCost.Carbonara * Double.parseDouble(jfCarbonara.getText());
        
        ItemCost.tWater = ItemCost.Water * Double.parseDouble(jfWater.getText());
        ItemCost.tJuice = ItemCost.Juice * Double.parseDouble(jfJuice.getText());
        ItemCost.tCoke = ItemCost.Coke * Double.parseDouble(jfCoke.getText());
        ItemCost.tCoffee = ItemCost.Coffee * Double.parseDouble(jfCoffee.getText());
        ItemCost.tHotChoco = ItemCost.HotChoco * Double.parseDouble(jfHotChoco.getText());
        ItemCost.tVanillaShake = ItemCost.VanillaShake * Double.parseDouble(jfVanillaShake.getText());
    
    String changevalue = jfPayment.getText();
     payment = Double.parseDouble(changevalue);
     
     iSubTotal = ItemCost.GetAmount();
     iTax = ItemCost.cFindTax(iSubTotal);
     iTotal = iSubTotal + iTax;
     
     
         String SubTotal = String.format("₱ %.2f", iSubTotal);
        jfSubTotal.setText(SubTotal);
        
        String Tax = String.format("₱ %.2f", iTax);
        jfTax.setText(Tax);
        
        String Total = String.format("₱ %.2f", iTotal);
        jfTotal.setText(Total);
        
        change = payment - iTotal;
  
    String Change = String.format("₱ %.2f", change);
    jfChange.setText(Change);

        
    }//GEN-LAST:event_BPayActionPerformed

    private void jfPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfPaymentActionPerformed

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        // TODO add your handling code here:
     
       try (FileWriter fw = new FileWriter("Receipt.txt", true);
         PrintWriter out = new PrintWriter(fw)) {

        int refs = 1325 + (int) (Math.random() * 4238);
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
        tDate.format(timer.getTime());

        out.println("\tRestaurant Management System\n\n" + "Reference:\t\t\t" + refs +
                "\n-------------------------------------------------\n" +
                "Item                            Amount" + "\n" +
                "\nCost of Meals:\t\t\t" + jfMeals.getText() + "\n\n" +
                "Cost of Drinks:\t\t\t" + jfDrinks.getText() + "\n\n" +
                "Total cost:\t\t\t" + jfMD.getText() + "\n\n" +
                "-------------------------------------------------" + "\n\n" +
                "VAT:\t\t\t\t" + jfTax.getText() + "\n\n" +
                "SubTotal:\t\t\t" + jfSubTotal.getText() + "\n\n" +
                "Total:\t\t\t\t" + jfTotal.getText() + "\n\n" +
                "-------------------------------------------------" + "\n\n" +
                "Cash:\t\t\t\t" + "₱ " + jfPayment.getText() + "\n\n\n" +
                "Change:\t\t\t\t" + jfChange.getText() + "\n\n\n" +
                "-------------------------------------------------" +
                "\nDate: " + tDate.format(timer.getTime()) +
                "\tTime: " + tTime.format(timer.getTime()) +
                "\n\nThank you.. Enjoy your Meal...");

        // No need to close resources explicitly, as try-with-resources statement takes care of it
    } catch (IOException ex) {
        ex.printStackTrace();
        Logger.getLogger(PosOOP.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_bPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PosOOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PosOOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PosOOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PosOOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new PosOOP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BExit;
    private javax.swing.JButton BPay;
    private javax.swing.JButton BReceipt;
    private javax.swing.JButton BReset;
    private javax.swing.JButton BTotal;
    private javax.swing.JButton bPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbPayment;
    private javax.swing.JTextField jfCarbonara;
    private javax.swing.JTextField jfChange;
    private javax.swing.JTextField jfCoffee;
    private javax.swing.JTextField jfCoke;
    private javax.swing.JTextField jfDrinks;
    private javax.swing.JTextField jfFriedChicken;
    private javax.swing.JTextField jfHotChoco;
    private javax.swing.JTextField jfJuice;
    private javax.swing.JTextField jfMD;
    private javax.swing.JTextField jfMeals;
    private javax.swing.JTextField jfPayment;
    private javax.swing.JTextField jfRice;
    private javax.swing.JTextField jfSinigang;
    private javax.swing.JTextField jfSisig;
    private javax.swing.JTextField jfSpag;
    private javax.swing.JTextField jfSubTotal;
    private javax.swing.JTextField jfTax;
    private javax.swing.JTextField jfTotal;
    private javax.swing.JTextField jfVanillaShake;
    private javax.swing.JTextField jfWater;
    private javax.swing.JLabel jtCarbonara;
    private javax.swing.JLabel jtChange;
    private javax.swing.JLabel jtCoffee;
    private javax.swing.JLabel jtCoke;
    private javax.swing.JLabel jtCostDrinks;
    private javax.swing.JLabel jtCostMeal;
    private javax.swing.JLabel jtFriedChicken;
    private javax.swing.JLabel jtHotChocolate;
    private javax.swing.JLabel jtOrangeJuice;
    private javax.swing.JLabel jtPorkSinigang;
    private javax.swing.JTextArea jtReceipt;
    private javax.swing.JLabel jtRice;
    private javax.swing.JLabel jtSisig;
    private javax.swing.JLabel jtSpaghetti;
    private javax.swing.JLabel jtSubTotal;
    private javax.swing.JLabel jtTax;
    private javax.swing.JLabel jtTax7;
    private javax.swing.JLabel jtTax9;
    private javax.swing.JLabel jtTotal;
    private javax.swing.JLabel jtTotalCost;
    private javax.swing.JLabel jtVanillaShake;
    private javax.swing.JLabel jtWater;
    // End of variables declaration//GEN-END:variables

    private void Change() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
